Agendas migrate Carto map
PopulateTools/gobierto-gencat-engine pull request #22
Opened 2020-10-30 12:09 UTC by jorgeatgu

Closes https://github.com/PopulateTools/issues/issues/1125

## :v: What does this PR do?

Migrate Carto map to d3 map.

## :mag: How should this be manually tested?

## :eyes: Screenshots

### After this PR

![gencat-map](https://user-images.githubusercontent.com/2649175/97703490-02984800-1ab1-11eb-829f-404bf9c953f7.gif)

2020-11-03 05:20 UTC, ferblape commented on app/javascripts/gencat/modules/gp_gencat_map_controller.js
> +  const dataGenCatTrips = 'https://gencat.gobify.net/api/v1/data/data.csv?sql=select%20*%20from%20trips'
Make this URL relative, to don't depend on the domain (in production is a different one)

2020-11-03 05:31 UTC, ferblape requested changes
![Screenshot 2020-11-03 at 06 26 07](https://user-images.githubusercontent.com/17616/97952395-81d19880-1d9d-11eb-8994-eabc0e743c5c.png)

- [x] Could you remove all the references to CARTO js and CARTO CSS?

- [x] The map for a department doesn't filter the events for that department, i.e https://gencat.gobify.net/ca/departments/departament-d-ensenyament?page=false&start_date=2018-06-01 See in the old code `${departmentCondition}` to filter by department

- [x] You are not filtering either by date, if I select a date range you are showing all the events, but it should be filtered by date. See ` ${dateRangeConditions}` in the old query

2020-11-03 13:32 UTC, ferblape commented
Hmmm, it's broken to me when I filter by department, there's a JS error: https://gencat.gobify.net/departamentos/departament-de-cultura?page=false&start_date=2019-11-03

2020-11-05 07:40 UTC, ferblape commented
Could you adapt the tooltip a bit to the different sizes? The new one is quite big if the content is just one or two trips, and in FF you can see the scroll:

![Screenshot 2020-11-05 at 08 38 54](https://user-images.githubusercontent.com/17616/98211543-7cfa1980-1f42-11eb-96fe-656f731501b4.png)

The old one looked much compact:

![Screenshot 2020-11-05 at 08 38 31](https://user-images.githubusercontent.com/17616/98211549-7e2b4680-1f42-11eb-95a0-aa96c33468f2.png)

2020-11-05 09:15 UTC, jorgeatgu commented
Done @blat!

![Screenshot 2020-11-05 at 10 15 07](https://user-images.githubusercontent.com/2649175/98221360-d1f05c80-1f4f-11eb-9f43-d8d7633f967e.png)

2020-11-07 06:43 UTC, merged